ui: remplace bootstrap by tailwindCSS
cogip/cogip-tools pull request #115
Opened 2024-08-31 11:22 UTC by Starbeuck

2024-08-31 16:55 UTC, gdoffe requested changes

2024-08-31 16:55 UTC, gdoffe commented on docs/developers/dashboard.md
> +TailwindCSS is a utility-first CSS framework packed with classes like flex, pt-4, text-center and rotate-90 that can be composed to build any design.
@Starbeuck I love you update documentation ! Thank you for that.

However it is not obvious why you did this commit that seems good to me.

Can you explain **in your commit message** why you decided to move from Bootstrap to TailwindCSS please ?

2025-01-16 20:51 UTC, ecourtois approved these changes
LGTM! Good job!

2025-01-16 20:56 UTC, ecourtois commented on docs/developers/dashboard.md
> +TailwindCSS is a utility-first CSS framework packed with classes like flex, pt-4, text-center and rotate-90 that can be composed to build any design.
Done

2025-01-17 15:47 UTC, gdoffe approved these changes
LGTM ! Good job !

2025-01-17 15:52 UTC, merged