Add driver for LD19 lidar
cogip/cogip-tools pull request #129
Opened 2024-12-23 16:00 UTC by ecourtois

2025-01-05 22:01 UTC, gdoffe requested changes
Few things but LGTM otherwise, nice job !

2025-01-05 22:17 UTC, gdoffe commented on cogip/cpp/drivers/lidar_ld19/include/lidar_ld19/ldlidar_protocol.h
> +};
Seen together, no need for Doxygen here.

2025-01-07 21:12 UTC, ecourtois commented on docker-compose.yml
> +  stop_signal: SIGKILL
After discussion, we keep SIGKILL, being in a development environment in a container, we don't need a clean exit.

2025-01-07 21:12 UTC, ecourtois commented on docker-compose.yml
> +  stop_signal: SIGKILL
Same

2025-01-11 14:24 UTC, gdoffe approved these changes
LGTM ! Good job !!!

2025-01-11 16:12 UTC, merged